datasets:
  # - name: yacht
  #   splits: 10
  # - name: autompg
  #   splits: 10
  # - name: concreteslump
  #   splits: 10
  # - name: 'energy'
  #   splits: 10
  # - name: 'forest'  # mierda
  #   splits: 10
  # - name: 'stock'
  #   splits: 10
  # - name: 'autos'   # mierda
  #   splits: 10
  # - name: 'breastcancer'
  #   splits: 10
  # - name: 'fertility'  # mierda
  #   splits: 10
  # - name: 'housing'
  #   splits: 10
  # - name: 'machine'
  #   splits: 10
  # - name: 'pendulum'
  #   splits: 10
  # - name: 'servo'  
  #   splits: 10
  # - name: concrete
  #   splits: 10
  - name: airfoil
    splits: 10  

parameters:
  num_experts: [2, 4, 6]
  validation_proportion: [0.05, 0.1]
fixed:
  kappa: 2   # suggested [2,100]
  lambdaa: 2 # suggested [1,10]

