/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 50 -i 0 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 50 -i 1 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 50 -i 2 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 50 -i 3 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 50 -i 4 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 50 -i 5 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 50 -i 6 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 50 -i 7 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 50 -i 8 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 50 -i 9 -D 'yacht' 


/usr/local/bin/python3 pogpe_mcmc_svi.py -M 6 -S 50 -i 0 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 6 -S 50 -i 1 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 6 -S 50 -i 2 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 6 -S 50 -i 3 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 6 -S 50 -i 4 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 6 -S 50 -i 5 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 6 -S 50 -i 6 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 6 -S 50 -i 7 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 6 -S 50 -i 8 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 6 -S 50 -i 9 -D 'yacht' 



/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 0 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 1 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 2 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 3 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 4 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 5 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 6 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 7 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 8 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 9 -D 'yacht' 


/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 0 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 1 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 2 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 3 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 4 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 5 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 6 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 7 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 8 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 8 -S 50 -i 9 -D 'yacht' 



/usr/local/bin/python3 pogpe_mcmc_svi.py -M 10 -S 50 -i 0 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 10 -S 50 -i 1 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 10 -S 50 -i 2 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 10 -S 50 -i 3 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 10 -S 50 -i 4 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 10 -S 50 -i 5 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 10 -S 50 -i 6 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 10 -S 50 -i 7 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 10 -S 50 -i 8 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 10 -S 50 -i 9 -D 'yacht' 