

/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 100 -i 0 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 100 -i 1 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 100 -i 2 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 100 -i 3 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 100 -i 4 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 100 -i 5 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 100 -i 6 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 100 -i 7 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 100 -i 8 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 100 -i 9 -D 'yacht' 

/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 150 -i 0 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 150 -i 1 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 150 -i 2 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 150 -i 3 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 150 -i 4 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 150 -i 5 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 150 -i 6 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 150 -i 7 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 150 -i 8 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 150 -i 9 -D 'yacht' 

/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 200 -i 0 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 200 -i 1 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 200 -i 2 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 200 -i 3 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 200 -i 4 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 200 -i 5 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 200 -i 6 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 200 -i 7 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 200 -i 8 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 200 -i 9 -D 'yacht' 


/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 300 -i 0 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 300 -i 1 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 300 -i 2 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 300 -i 3 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 300 -i 4 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 300 -i 5 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 300 -i 6 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 300 -i 7 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 300 -i 8 -D 'yacht' 
/usr/local/bin/python3 pogpe_mcmc_svi.py -M 4 -S 300 -i 9 -D 'yacht' 